config:
  tools:
    gitlab: http://gitlab.xxx.com/
    jenkins: http://jenkins.xxx.com/
    nexus: http://nexus.xxx.com/
    harbor: http://harbor.xxx.com/
    sonarqube: http://sonarqube.xxx.com/
    grafana: http://grafana.xxx.com/

  kubernetes_manage_tools:
    rainbond_ui: http://rainbond.xxx.com/
    kubernetes_ui: https://k8sui.xxx.com/
